### ISSUE TITLE
Allow user to set a working directory

### ISSUE THREAD

**Issue by ghost** [karma-runner/karma-intellij#21]
I just ran into the problem that the "karma-chai-plugins" plugin uses the working directory to resolve a path. There is no way to set this in this plugin. Please add it to the configuration settings, just like when creating a node.js configuration.

**Comment by jvmccarthy** [comment]
Sorry to come by many years later on this issue, but I just ran into it. I also have `karma.conf.js` in a nested directory and wish I could control the working directory from the IntelliJ launcher. As a workaround, I call `process.chdir()` early in `karma.conf.js` to set the directory to the project root directory. Having the ability to set the working directory in an IntelliJ launcher is not uncommon, as the JUnit launcher allows for this.

In my case, this was causing issues because I had `.eslintignore` in the root directory of the project. Having IntelliJ run karma in a different working directory was causing issues with eslint not finding the ignore file, leading to eslint warnings that I don't see when running with `npm run`.

**Comment by segrey** [comment]
@jvmccarthy Please follow https://youtrack.jetbrains.com/issue/WEB-16577 for updates
